### ISSUE TITLE
Please add license and Travis CI to project

### ISSUE THREAD

**Issue by JohnReedLOL** [cb372/sbt-write-output-to-file#2]
Please add a license file (MIT or Apache 2.0) and Travis CI to the project.

Example of Travis CI: https://github.com/banana-rdf/banana-rdf/issues/345

Example of LICENSE file: https://github.com/wartremover/wartremover/issues/437

**Comment by cb372** [comment]
Done.

**Comment by JohnReedLOL** [comment]
Can you add Scala 2.11.8 to the travis.yaml and add the little Markdown sticker that says "build passing" to the README?

**Comment by cb372** [comment]
Umm... PRs welcome

**Comment by cb372** [comment]
Also, why 2.11.8? This is an sbt plugin and sbt uses Scala 2.12.

**Comment by JohnReedLOL** [comment]
@cbs372 - The reason you need to build things for both Scala 2.11 and Scala 2.12 is because Scala libraries/jars are not backwards or forwards compatible. I would recommend that you read the sbt documentation, and in particular read the following sections:

- https://www.scala-sbt.org/1.0/docs/Cross-Build.html
- https://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html
- https://www.scala-sbt.org/1.0/docs/Cross-Build-Plugins.html
